# Generated by Django 5.2.17 on 2026-09-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telegram_group_id', models.BigIntegerField(help_text="Restoran Telegram guruhi ID'si")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_tg_id', models.BigIntegerField()),
                ('courier_tg_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('ready', 'Tayyor (Kuryer kutilmoqda)'), ('delivering', "Yo'lda"), ('completed', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='created', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant_msg_id', models.IntegerField(blank=True, null=True)),
                ('courier_msg_id', models.IntegerField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.restaurant')),
            ],
        ),
    ]
