# Generated by Django 5.2.15 on 2026-09-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_category_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Yetkazib berilganda (Naqd)'), ('card_delivery', 'Yetkazib berilganda (Karta)'), ('card_now', 'Karta orqali hoziroq')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot_url',
            field=models.CharField(blank=True, help_text="To'lov skrinshoti Telegram file_id yoki URL", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='card_number',
            field=models.CharField(blank=True, help_text='Restoranning plastik karta raqami', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='card_owner_name',
            field=models.CharField(blank=True, help_text='Karta egasining ism-familiyasi', max_length=150, null=True),
        ),
    ]
