# Generated by Django 5.2.15 on 2026-09-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_paid_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Yetkazib berilganda (Naqd)'), ('card_delivery', 'Yetkazib berilganda (Karta)'), ('card_now', 'Karta orqali hoziroq')], default='cash', max_length=150),
        ),
    ]
