# Generated by Django 5.2.15 on 2026-09-12 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Taom rasmi', upload_to='menu_images/')),
                ('is_main', models.BooleanField(default=False, help_text='Asosiy rasm (faqat 1 ta bo_lishi tavsiya etiladi)')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.menuitem')),
            ],
        ),
    ]
