# Generated by Django 5.2.15 on 2026-09-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Taom faol (mavjud) bo'lsa True, vaqtincha mavjud emas bo'lsa False"),
        ),
    ]
