# Generated by Django 5.2.15 on 2026-09-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_working_hours_to_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, help_text="Kuryerning to'liq ismi (snapshot)", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_username',
            field=models.CharField(blank=True, help_text="Kuryerning Telegram username'i (snapshot)", max_length=100, null=True),
        ),
    ]
