# Generated by Django 5.2.15 on 2026-09-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Restoran bilan aloqa uchun telefon raqami', max_length=20, null=True),
        ),
    ]
