# Generated by Django 5.2.15 on 2026-09-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_restaurant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Kutilmoqda'), ('waiting_payment', "To'lov kutilmoqda"), ('accepted', 'Qabul qilindi'), ('ready', 'Tayyor (Kuryer kutilmoqda)'), ('delivering', "Yo'lda"), ('completed', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='created', max_length=20),
        ),
    ]
