# Generated by Django 5.2.15 on 2026-09-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text="To'lov skrinshoti rasmi", null=True, upload_to='payment_screenshots/'),
        ),
    ]
