# Generated by Django 5.2.15 on 2026-09-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partial_accept_msg_id',
            field=models.IntegerField(blank=True, help_text="Mijozga yuborilgan 'Qisman qabul' xabari ID si", null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Restoran tomonidan olib tashlangan taom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Kutilmoqda'), ('waiting_payment', "To'lov kutilmoqda"), ('partial_pending', 'Qisman qabul — Mijoz javobi kutilmoqda'), ('accepted', 'Qabul qilindi'), ('ready', 'Tayyor (Kuryer kutilmoqda)'), ('delivering', "Yo'lda"), ('completed', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='created', max_length=20),
        ),
    ]
